# This is a basic workflow to help you get started with Actions

name: matrix

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{  steps.filter.outputs.changes }}   
    steps:
    - uses: actions/checkout@v2
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          src:
            - 'src/**'

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: detect-changes
#     if: needs.detect-changes.outputs.projects  != '[]'
    if: ''
    strategy:
      matrix:
        project: ${{ fromJSON(needs.detect-changes.outputs.projects) }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ needs.detect-changes.outputs.projects }}
